: "${XDG_CONFIG_HOME:=$HOME/.config}"
: "${XDG_CACHE_HOME:=$HOME/.cache}"
: "${XDG_STATE_HOME:=$HOME/.local/state}"
: "${XDG_DATA_HOME:=$HOME/.local/share}"
: "${NPM_CONFIG_USERCONFIG:=$XDG_CONFIG_HOME/npm/npmrc}"
: "${NPM_CONFIG_CACHE:=$XDG_CACHE_HOME/npm}"
: "${GOPATH:=$XDG_DATA_HOME/go}"
: "${GOCACHE:=$XDG_CACHE_HOME/go-build}"
: "${GOMODCACHE:=$XDG_DATA_HOME/go/pkg/mod}"
: "${GOBIN:=$HOME/.local/bin}"

export XDG_CONFIG_HOME XDG_CACHE_HOME XDG_STATE_HOME XDG_DATA_HOME
export NPM_CONFIG_USERCONFIG NPM_CONFIG_CACHE
export GOPATH GOCACHE GOMODCACHE GOBIN

ZDOTDIR="$XDG_CONFIG_HOME/zsh"

SHELL_SESSIONS_DISABLE=1
