" -----------------------------
" xdg
" -----------------------------
set runtimepath+=$XDG_DATA_HOME/vim
set packpath+=$XDG_DATA_HOME/vim,$XDG_DATA_HOME/vim/after
set backupdir=$XDG_STATE_HOME/vim/backup
set directory=$XDG_STATE_HOME/vim/swap
set viewdir=$XDG_STATE_HOME/vim/view
set undodir=$XDG_STATE_HOME/vim/undo
set viminfofile=$XDG_STATE_HOME/vim/viminfo

" -----------------------------
" vim
" -----------------------------

set nocompatible                      " disable compatible mode

set tabstop=2                         " tab width
set shiftwidth=2                      " indent width
set list                              " visiblize tabs
set listchars=tab:.\ ,trail:.         " tab => spaces set list
set expandtab                         " tab => spaces

set number                            " show line number
set ruler                             " show cursor status
set cursorline                        " highlight current line
set showcmd                           " show commands
set showmatch                         " match parentheses

set clipboard^=unnamed,unnamedplus    " allow copy-paste everywhere

set backspace=indent,eol,start

set background=dark

syntax on
filetype plugin indent on
